# These are supported funding model platforms

github: Turbo87
patreon: # Replace with a single Patreon username
open_collective: skylines
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://paypal.me/tobiasbieniek # Replace with a single custom sponsorship URL
