# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  CI: true
  JOBS: 1  # See https://git.io/vdao3 for details.

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      curl -o- -L https://yarnpkg.com/install.sh | bash
      export PATH=$HOME/.yarn/bin:$PATH
    displayName: 'Install Yarn'

  - script: |
      yarn install --non-interactive
    displayName: 'Install dependencies'

  - script: |
      yarn lint:hbs
      yarn lint:js
    displayName: 'Run linting checks'

  - script: |
      yarn test --testem-debug=test.log
    displayName: 'Run tests'
    continueOnError: true

  - script: |
      cat test.log
